numbers = [30, 10, 50, 20, 40]
print("Original List:", numbers)
numbers.append(60)
print("After append():", numbers)
numbers.insert(2, 25)
print("After insert():", numbers)
numbers.remove(10)
print("After remove():", numbers)
numbers.pop()
print("After pop():", numbers)
numbers.sort()
print("After sort():", numbers)
